// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'body': string;
  'btnIcon': string;
  'button': string;
  'buyInfo': string;
  'card': string;
  'content': string;
  'header': string;
  'icon': string;
  'list': string;
  'subHeader': string;
  'watchAds': string;
}
export const cssExports: CssExports;
export default cssExports;
