// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'code': string;
  'input': string;
  'ref': string;
  'refPanel': string;
  'snackbar': string;
}
export const cssExports: CssExports;
export default cssExports;
