// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'dark': string;
  'headline': string;
  'subHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
