// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'blur': string;
  'images': string;
  'left': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
