// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'card': string;
  'name': string;
  'rating': string;
  'topNumber': string;
  'transferIcon': string;
  'userItem': string;
}
export const cssExports: CssExports;
export default cssExports;
