// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'achievement': string;
  'avatar': string;
  'levels': string;
  'numbers': string;
  'progress': string;
  'progressWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
