// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance': string;
  'button': string;
  'items': string;
  'topNumber': string;
  'userItem': string;
}
export const cssExports: CssExports;
export default cssExports;
