// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'achievement': string;
  'actions': string;
  'body': string;
  'btnWithInfo': string;
  'card': string;
  'icon': string;
  'info': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
