// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'card': string;
}
export const cssExports: CssExports;
export default cssExports;
