// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'content': string;
  'info': string;
  'modal': string;
}
export const cssExports: CssExports;
export default cssExports;
