// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'copy': string;
  'copyItem': string;
  'header': string;
  'item': string;
  'list': string;
  'mini': string;
  'modal': string;
  'recent': string;
  'shareItem': string;
}
export const cssExports: CssExports;
export default cssExports;
