// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'icon1': string;
  'icon2': string;
  'icon3': string;
  'icon4': string;
  'icon5': string;
}
export const cssExports: CssExports;
export default cssExports;
