// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'fire': string;
  'img': string;
  'middle': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
