// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance': string;
  'bg': string;
  'blur': string;
  'icon': string;
  'iconWithProgress': string;
  'images': string;
  'info': string;
  'left': string;
  'progress': string;
  'pulse': string;
  'right': string;
  'stat': string;
}
export const cssExports: CssExports;
export default cssExports;
