// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance': string;
  'game': string;
  'icon': string;
  'iconWithProgress': string;
  'info': string;
  'progress': string;
  'pulse': string;
  'stat': string;
}
export const cssExports: CssExports;
export default cssExports;
