// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'topNumber': string;
  'users': string;
  'usersItem': string;
}
export const cssExports: CssExports;
export default cssExports;
