// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'improvements': string;
  'user': string;
}
export const cssExports: CssExports;
export default cssExports;
